name: admin_proteinas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  animate_do: ^3.3.4
  cloud_firestore: ^5.3.0
  equatable: ^2.0.5
  firebase_auth: ^5.2.0
  firebase_core: ^3.6.0
  firebase_storage: ^12.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  flutter_spinkit: ^5.2.1
  formz: ^0.7.0
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  uuid: ^4.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/proteinas.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#080808"
  android_12:
    color: "#080808"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
